services:
  - type: web
    name: shock-beatzs-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: JWT_SECRET
        value: "replace_with_secure_value"
